from django.core.management.base import BaseCommand
from study.models import QuestionSet, Question


class Command(BaseCommand):
    help = "Create EduChamp dummy questions"

    def handle(self, *args, **kwargs):
        questions = [
            # Mathematics - Geometry
            {
                "module": "geometry",
                "question": "How many sides does a triangle have?",
                "a": "2",
                "b": "3",
                "c": "4",
                "d": "5",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "geometry",
                "question": "A square has how many equal sides?",
                "a": "2",
                "b": "3",
                "c": "4",
                "d": "5",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "geometry",
                "question": "What is the sum of angles in a triangle?",
                "a": "90°",
                "b": "180°",
                "c": "270°",
                "d": "360°",
                "answer": "B",
                "difficulty": "medium",
            },
            {
                "module": "geometry",
                "question": "How many degrees are in a right angle?",
                "a": "45°",
                "b": "60°",
                "c": "90°",
                "d": "180°",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "geometry",
                "question": "A circle has how many sides?",
                "a": "0",
                "b": "1",
                "c": "2",
                "d": "4",
                "answer": "A",
                "difficulty": "easy",
            },

            # Mathematics - Algebra
            {
                "module": "algebra",
                "question": "What is x + 5 = 10?",
                "a": "3",
                "b": "4",
                "c": "5",
                "d": "6",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "algebra",
                "question": "What is 2x when x = 4?",
                "a": "4",
                "b": "6",
                "c": "8",
                "d": "10",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "algebra",
                "question": "If x - 3 = 7, what is x?",
                "a": "4",
                "b": "7",
                "c": "10",
                "d": "12",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "algebra",
                "question": "What is 3x + 2 when x = 2?",
                "a": "6",
                "b": "8",
                "c": "10",
                "d": "12",
                "answer": "B",
                "difficulty": "medium",
            },
            {
                "module": "algebra",
                "question": "If 2x = 18, x equals:",
                "a": "6",
                "b": "8",
                "c": "9",
                "d": "12",
                "answer": "C",
                "difficulty": "medium",
            },

            # Science - EVS
            {
                "module": "EVS",
                "question": "Which planet do we live on?",
                "a": "Mars",
                "b": "Earth",
                "c": "Venus",
                "d": "Jupiter",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "EVS",
                "question": "Which gas do humans need for breathing?",
                "a": "Oxygen",
                "b": "Nitrogen",
                "c": "Carbon dioxide",
                "d": "Hydrogen",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "EVS",
                "question": "Which is a renewable source of energy?",
                "a": "Coal",
                "b": "Petroleum",
                "c": "Solar energy",
                "d": "Natural gas",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "EVS",
                "question": "Which part of a plant absorbs water from soil?",
                "a": "Leaf",
                "b": "Flower",
                "c": "Root",
                "d": "Fruit",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "EVS",
                "question": "What is the main cause of day and night?",
                "a": "Earth's rotation",
                "b": "Earth's revolution",
                "c": "Moon's rotation",
                "d": "Sun's movement",
                "answer": "A",
                "difficulty": "medium",
            },

            # Science - Physics
            {
                "module": "phsyics",
                "question": "What force pulls objects toward Earth?",
                "a": "Friction",
                "b": "Gravity",
                "c": "Magnetism",
                "d": "Pressure",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "phsyics",
                "question": "What is the SI unit of force?",
                "a": "Joule",
                "b": "Watt",
                "c": "Newton",
                "d": "Pascal",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "phsyics",
                "question": "Which travels fastest?",
                "a": "Sound",
                "b": "Light",
                "c": "Water",
                "d": "Wind",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "phsyics",
                "question": "What instrument measures temperature?",
                "a": "Barometer",
                "b": "Thermometer",
                "c": "Ammeter",
                "d": "Voltmeter",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "phsyics",
                "question": "Which energy does a moving object possess?",
                "a": "Potential",
                "b": "Chemical",
                "c": "Kinetic",
                "d": "Nuclear",
                "answer": "C",
                "difficulty": "medium",
            },

            # English - Literature
            {
                "module": "Literature",
                "question": "Who wrote Romeo and Juliet?",
                "a": "Charles Dickens",
                "b": "William Shakespeare",
                "c": "Jane Austen",
                "d": "Mark Twain",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "Literature",
                "question": "A story with animals that teaches a lesson is called a:",
                "a": "Fable",
                "b": "Novel",
                "c": "Biography",
                "d": "Essay",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "Literature",
                "question": "Who wrote The Jungle Book?",
                "a": "Rudyard Kipling",
                "b": "William Shakespeare",
                "c": "George Orwell",
                "d": "J.K. Rowling",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "Literature",
                "question": "A poem is usually divided into groups of lines called:",
                "a": "Chapters",
                "b": "Stanzas",
                "c": "Paragraphs",
                "d": "Acts",
                "answer": "B",
                "difficulty": "medium",
            },
            {
                "module": "Literature",
                "question": "Who wrote Pride and Prejudice?",
                "a": "Jane Austen",
                "b": "Emily Brontë",
                "c": "Virginia Woolf",
                "d": "Agatha Christie",
                "answer": "A",
                "difficulty": "medium",
            },

            # English - Grammar
            {
                "module": "Grammar",
                "question": "Which word is a noun?",
                "a": "Run",
                "b": "Beautiful",
                "c": "School",
                "d": "Quickly",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "Grammar",
                "question": "Choose the correct sentence:",
                "a": "He go to school.",
                "b": "He goes to school.",
                "c": "He going school.",
                "d": "He gone school.",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "Grammar",
                "question": "What is the past tense of go?",
                "a": "Goed",
                "b": "Going",
                "c": "Went",
                "d": "Gone",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "Grammar",
                "question": "Which word is an adjective?",
                "a": "Quickly",
                "b": "Beautiful",
                "c": "Run",
                "d": "Happiness",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "Grammar",
                "question": "Identify the pronoun: She is reading a book.",
                "a": "reading",
                "b": "book",
                "c": "She",
                "d": "is",
                "answer": "C",
                "difficulty": "easy",
            },

            # Computer Science - Hardware
            {
                "module": "Hardware",
                "question": "Which component is known as the brain of the computer?",
                "a": "RAM",
                "b": "CPU",
                "c": "Monitor",
                "d": "Keyboard",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "Hardware",
                "question": "Which device is used to enter text?",
                "a": "Monitor",
                "b": "Printer",
                "c": "Keyboard",
                "d": "Speaker",
                "answer": "C",
                "difficulty": "easy",
            },
            {
                "module": "Hardware",
                "question": "Which device displays visual output?",
                "a": "Monitor",
                "b": "Mouse",
                "c": "Keyboard",
                "d": "CPU",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "Hardware",
                "question": "RAM is primarily used for:",
                "a": "Permanent storage",
                "b": "Temporary data storage",
                "c": "Printing",
                "d": "Internet connection",
                "answer": "B",
                "difficulty": "medium",
            },
            {
                "module": "Hardware",
                "question": "Which is an example of secondary storage?",
                "a": "RAM",
                "b": "Cache",
                "c": "Hard disk",
                "d": "CPU",
                "answer": "C",
                "difficulty": "easy",
            },

            # Computer Science - Software
            {
                "module": "Software",
                "question": "Which is an operating system?",
                "a": "Windows",
                "b": "Google",
                "c": "Python",
                "d": "HTML",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "Software",
                "question": "Which language is commonly used for web page structure?",
                "a": "HTML",
                "b": "Python",
                "c": "SQL",
                "d": "C++",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "Software",
                "question": "Which of these is a programming language?",
                "a": "Python",
                "b": "Windows",
                "c": "Chrome",
                "d": "Linux",
                "answer": "A",
                "difficulty": "easy",
            },
            {
                "module": "Software",
                "question": "What does SQL primarily work with?",
                "a": "Images",
                "b": "Databases",
                "c": "Hardware",
                "d": "Audio",
                "answer": "B",
                "difficulty": "easy",
            },
            {
                "module": "Software",
                "question": "Which is a web browser?",
                "a": "Chrome",
                "b": "Linux",
                "c": "Python",
                "d": "MySQL",
                "answer": "A",
                "difficulty": "easy",
            },
        ]

        for item in questions:
            module = item["module"]

            question_set = QuestionSet.objects.get(
                module__name__iexact=module,
                set_number=1
            )

            Question.objects.get_or_create(
                question_set=question_set,
                text=item["question"],
                defaults={
                    "option_a": item["a"],
                    "option_b": item["b"],
                    "option_c": item["c"],
                    "option_d": item["d"],
                    "correct_answer": item["answer"],
                    "difficulty": item["difficulty"],
                }
            )

        self.stdout.write(
            self.style.SUCCESS("Questions created successfully!")
        )